### ISSUE TITLE
Unable to open after update

### ISSUE THREAD

**Issue by DF001** [aarnt/octopi#519]
Get Error when trying to open on any arch distro. Tried it on GarudaOS and AthenaOS:

`octopi: undefined symbol: _ZN11QTermWidget20setScrollBarPositionENS_17ScrollBarPositionE`

**Comment by shibedrill** [comment]
Same exact issue here. EndeavourOS, QT version 5.15.7.

**Comment by simona70** [comment]
same problem

**Comment by aarnt** [comment]
@simona70 
Hi. Your distro probably compiled  octopi with qtermwidget 1.1.0. After that, it may have shipped qtermwidget 1.2.0, but octopi pkg was not recompiled, so the linker can't find the calls to the qterm libs.

**Comment by frozenemitt** [comment]
In Arch Linux the same issue was fixed by rebuilding and reinstalling octopi after the qtermwidget 1.2.0 update.

**Comment by demmm** [comment]
@shibedrill 
>If you want to fix it, you can downgrade it by installing the AUR version which is still version 0.14.0-1.

The version doesn't fix, it is the fact you rebuild on the correct (new, 1.2.0) version of qtermwidget that resolved the issue.

**Comment by simona70** [comment]
definitely fixed?

**Comment by demmm** [comment]
> definitely fixed?

Make sure to read the responses here, you are NOT facing an Octopi issue, you need a rebuild since you/your distro updated an underlying library (from qtermwidget).
